import Footer from "@/components/footer/footer";
import NavBar from "@/components/nav-menu/nav-menu";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen m-0 p-0 flex justify-center ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-full w-4/5 m-0 p-0 flex flex-col">
          <header className="mt-3 mb-5 p-1 flex justify-center rounded-lg border border-gray-200 shadow-md">
            <NavBar />
          </header>
          <main className="flex flex-grow p-5 rounded-lg border border-gray-200 shadow-lg overflow-hidden">
            {children}
          </main>
          <footer className="mt-5 mb-7">
            <Footer />
          </footer>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
